begin;
select plan(21);
select has_table('public', 'staff_access_profiles', 'named staff profiles exist');
select has_table('public', 'staff_property_access', 'staff property scope is normalized');
select has_table('public', 'staff_access_audit', 'staff access audit exists');
select has_column('public', 'staff_access_profiles', 'sessions_revoked_after', 'profile supports global session revocation');
select has_function('public', 'staff_access_allowed', array['text','text','timestamp with time zone','text'], 'access decision function exists');
select has_function('public', 'current_staff_authorized', array['text','uuid'], 'current-session authorization function exists');
select has_function('public', 'current_staff_access', array[]::text[], 'self access projection exists');
select has_function('public', 'manage_staff_access', array['uuid','text','text','uuid[]','text'], 'guarded staff management function exists');
select has_function('public', 'bootstrap_cascade_owner', array['uuid','uuid[]','text'], 'one-time owner bootstrap exists');
select ok(not has_table_privilege('anon', 'public.staff_access_profiles', 'select'), 'anon cannot read staff roles');
select ok(not has_table_privilege('authenticated', 'public.staff_access_profiles', 'select'), 'authenticated clients cannot enumerate staff roles');
select ok(has_table_privilege('service_role', 'public.staff_access_audit', 'select'), 'service role may read staff audit');
select ok(has_table_privilege('service_role', 'public.staff_access_audit', 'insert'), 'service role may append staff audit');
select ok(not has_table_privilege('service_role', 'public.staff_access_audit', 'update'), 'staff audit cannot be updated by service role');
select ok(has_function_privilege('authenticated', 'public.manage_staff_access(uuid,text,text,uuid[],text)', 'execute'), 'authenticated staff may enter guarded management RPC');
select ok(not has_function_privilege('service_role', 'public.bootstrap_cascade_owner(uuid,uuid[],text)', 'execute'), 'service role cannot bootstrap an owner');
select ok(public.staff_access_allowed('cleaner','submit_cleaning',null,'aal1'), 'active cleaner may submit');
select ok(not public.staff_access_allowed('cleaner','submit_cleaning',now(),'aal1'), 'disabled cleaner cannot submit');
select ok(not public.staff_access_allowed('inspector','approve_payment',null,'aal2'), 'inspector cannot approve payment');
select ok(not public.staff_access_allowed('admin','approve_payment',null,'aal1'), 'payment approval requires AAL2');
select ok(not public.staff_access_allowed('admin','approve_payment',null,null), 'missing assurance level fails closed');
select * from finish();
rollback;
