param([string]$Container='supabase_db_direct-booking')
$ErrorActionPreference='Stop';$root=(Resolve-Path(Join-Path $PSScriptRoot '../..')).Path;$db='cascade_wave6_rollback';$dump='/tmp/cascade-wave6-rollback.dump'
$migration=Get-Content -Raw(Join-Path $root 'supabase/migrations/20260905080000_crm_consent_lifecycle.sql');$suite=Get-Content -Raw(Join-Path $root 'supabase/tests/database/crm_consent_lifecycle.sql');$rollback=Get-Content -Raw(Join-Path $root 'supabase/rollbacks/20260905080000_crm_consent_lifecycle.sql')
function D([string[]]$a){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';try{$o=& docker @a 2>&1;$x=$LASTEXITCODE}finally{$ErrorActionPreference=$old};if($x){throw($o-join"`n")};return $o}
if($suite-notmatch'^begin;' -or $suite-notmatch'rollback;\s*$'){throw 'Rollback-only suite required'}
$o=("begin;`n"+$migration+$suite.Substring(6))|docker exec -i $Container psql -X -A -t -v ON_ERROR_STOP=1 -U postgres -d postgres 2>&1
if($LASTEXITCODE -or ($o-join"`n")-match'(?m)^not ok|Looks like you'){throw($o-join"`n")};if(($o-join"`n")-notmatch'(?m)^1\.\.31\s*$' -or @($o|?{$_-match'^ok \d+'}).Count-ne 31){throw 'Expected 31 pgTAP assertions'};Write-Output 'Wave 6 pgTAP passed: 31/31; candidate DDL and fixtures rolled back.'
try{D @('exec',$Container,'pg_dump','--format=custom','--no-owner','--no-privileges','-U','postgres','-d','postgres','-f',$dump)|Out-Null;D @('exec',$Container,'dropdb','--if-exists','--force','-U','postgres',$db)|Out-Null;D @('exec',$Container,'createdb','-U','postgres',$db)|Out-Null;D @('exec',$Container,'pg_restore','--no-owner','--no-privileges','--exclude-schema=realtime','--exclude-schema=vault','-U','postgres','-d',$db,$dump)|Out-Null
 $migration|docker exec -i $Container psql -X -v ON_ERROR_STOP=1 -U postgres -d $db|Out-Null;if($LASTEXITCODE){throw 'Migration failed'};$rollback|docker exec -i $Container psql -X -v ON_ERROR_STOP=1 -U postgres -d $db|Out-Null;if($LASTEXITCODE){throw 'Rollback failed'}
 $c=D @('exec',$Container,'psql','-X','-A','-t','-U','postgres','-d',$db,'-c',"select to_regclass('public.crm_guest_profiles') is null and to_regclass('public.crm_consent_events') is null and to_regprocedure('public.crm_marketing_eligible(uuid)') is null");if(($c|select -Last 1).Trim()-ne't'){throw 'Rollback left objects'};Write-Output 'Wave 6 compensating rollback passed in a disposable restored database.'
}finally{$old=$ErrorActionPreference;$ErrorActionPreference='Continue';docker exec $Container dropdb --if-exists --force -U postgres $db 2>&1|Out-Null;docker exec $Container rm -f $dump 2>&1|Out-Null;$ErrorActionPreference=$old}
