-- 20260929010000_house_facts.sql
-- Session 60, D-282 (DESIGN-house-knowledge-2026-09-29): release house_facts_20260929.
--   house_facts                        how-to facts Cassy reads at runtime (Messenger + Telegram); service role only.
--                                      tier public = anyone on Messenger; guest = a verified current guest; staff = Telegram.
--                                      {{WIFI_SSID}} {{WIFI_PASSWORD}} {{ONGROUND}} are filled from app_settings at runtime.
--   concierge_threads.verified_until   the thread passed the welcome guide's check (verify_booking + stay on today);
--                                      guest-tier rows stay open through this date (the stay's check-out).
-- Seed: SEED-house-knowledge-2026-09-29 with Lloyd's answers of 2026-09-29 applied. Keywords were narrowed where a
-- common word would lock a prospect out ("code", "pin", "qr", "gate", "card", "1000"); plain "wifi" also sits on the
-- public row so "is there wifi?" is answered, while "wifi password" asks for the stay.
-- The door PIN, payment numbers and logins are never rows.

begin;

create table if not exists public.house_facts (
  topic       text primary key,
  title       text not null,
  body        text not null,
  keywords    text[] not null default '{}',
  tier        text not null default 'guest' check (tier in ('public', 'guest', 'staff')),
  is_active   boolean not null default true,
  updated_by  text,
  updated_at  timestamptz not null default now()
);

alter table public.house_facts enable row level security;
-- No policy for anon or authenticated: Edge Functions (service role) only, like admin_auth_attempts.
revoke all on table public.house_facts from public, anon, authenticated;
grant select, insert, update, delete on table public.house_facts to service_role;

alter table public.concierge_threads add column if not exists verified_until date;

insert into public.house_facts (topic, title, tier, keywords, body, updated_by) values
('aircon', 'Aircon (TCL 2.5 HP split-type)', 'public',
 array['aircon','ac','air con','airconditioner','air conditioning','cold','hot room','temperature','remote','cool mode','dry mode','sleep mode','eco','swing','timer','malamig','mainit','init','tugnaw'],
 $b$The unit is already running when you arrive; the remote is kept with the key card. A comfortable setting is 26 C on COOL with the fan on AUTO. The MODE button cycles COOL (everyday cooling), FAN (air only), DRY (takes the humidity out on rainy days) and AUTO (holds the set temperature). SLEEP raises the temperature 1 C an hour overnight, ECO trims power use, SWING moves the louver, and TIMER switches the unit off after the hours you set.$b$, 'seed 2026-09-29'),
('aircon-turnover', 'Aircon at turnover (staff)', 'staff',
 array['aircon standby','28','vacant','turnover aircon','aircon off'],
 $b$At check-out set the aircon to 28 C so the unit rests on standby and saves power. Switch it fully off when the unit will be vacant for 24 hours or more, and back on before the next arrival so the room is cool when the guest walks in.$b$, 'seed 2026-09-29'),
('tv', 'Smart TV (Samsung 55")', 'public',
 array['tv','television','netflix','youtube','youtube premium','samsung tv plus','channels','streaming','remote','hdmi','source','input','screen mirror','screen mirroring','cast','viu','login screen','sign in'],
 $b$The TV remote is kept with the key card. Power is at the top of the remote (hold it for three seconds if the set is slow to wake); volume is the right rocker, channels the left. Home opens the Smart Hub, where Netflix, YouTube Premium, Viu and Samsung TV Plus live channels are signed in and ready. Source switches to HDMI 1 or 2, and screen mirroring from your phone is under Settings > General > External Device Manager. If a login screen ever appears, a message to us saves you the trouble - the saved accounts are best left as they are.$b$, 'seed 2026-09-29'),
('wifi', 'Wi-Fi', 'guest',
 array['wifi','wi-fi','password','ssid','wifi password','wi-fi password','network name','wifi name','qr card'],
 $b$The network is {{WIFI_SSID}} and the password is {{WIFI_PASSWORD}}. It is fibre broadband, so calls and streaming are comfortable, and the QR card in the unit connects your phone in one scan. The router runs on backup power, so the connection stays up through a brownout.$b$, 'seed 2026-09-29'),
('wifi-name', 'Wi-Fi, for prospects', 'public',
 array['wifi','wi-fi','internet','wifi speed','internet speed','work from home','video call','zoom','remote work','fast internet','fibre','fiber'],
 $b$The unit has fibre broadband Wi-Fi with a dedicated workspace, so video calls, remote work and streaming are comfortable. The router has backup power and stays up during a brownout. The network details are in the unit and in the welcome guide once your stay begins.$b$, 'seed 2026-09-29'),
('wifi-down', 'Wi-Fi not working', 'public',
 array['wifi down','no internet','internet not working','slow internet','router','disconnected','walang internet','walay internet','no wifi'],
 $b$The first fix is the router: unplug it, wait a full sixty seconds, and plug it back in. Give it two or three minutes to come back. If the connection is still down after that, send us a word and we will check with the provider for an outage in the area while looking at other options for you.$b$, 'seed 2026-09-29'),
('wifi-down-staff', 'Wi-Fi down, next steps (staff)', 'staff',
 array['wifi playbook','isp','outage','hotspot','coworking'],
 $b$Once the guest has power-cycled the router for sixty seconds, check the ISP app for an area outage and update the guest within fifteen minutes. If it persists, offer a mobile hotspot or a co-working pass and log it for Lloyd.$b$, 'seed 2026-09-29'),
('water-heater', 'Water heater (Panasonic)', 'public',
 array['water heater','heater','hot water','warm water','no hot water','shower','mainit na tubig','init tubig','shower heater'],
 $b$Flip the heater's wall switch on before your shower and allow three to five minutes for the hot water to reach the shower head. The red light means it is heating; once it turns off or green, the water is at temperature. The dial turns clockwise for hotter and anticlockwise for cooler. Switching it off after your shower saves power, and it should stay off whenever the water supply itself is off.$b$, 'seed 2026-09-29'),
('water-heater-turnover', 'Water heater at turnover (staff)', 'staff',
 array['heater turnover','heater off','heater on','dry heating'],
 $b$Switch the heater off after every check-out and on again ten to fifteen minutes before the next check-in. Never switch it on while the water supply is off; dry heating damages the element.$b$, 'seed 2026-09-29'),
('shower', 'Hot and cold shower', 'public',
 array['shower','bath','towel','towels','ensuite','bathroom','cold shower','ligo','kaligo'],
 $b$The private ensuite has a full hot and cold shower. For warm water, switch the heater on and give it three to five minutes; for a cool rinse, leave the heater off. Hotel-quality towels are provided.$b$, 'seed 2026-09-29'),
('induction-cooker', 'Induction cooker (Dowell)', 'public',
 array['induction','cooker','stove','cook','cooking','pan','pot','kawali','luto','magluto','hob','burner'],
 $b$Place a pan on the centre of the glass, press POWER, then use + and - for the power level; four or five suits everyday cooking, and TIMER switches it off after a set time. The pans provided all work on it; a pan of your own needs a magnetic base or the coil symbol underneath. It beeps and shuts off on its own after sixty seconds without a pan. The glass stays cool around the pan, and a damp cloth cleans it once it has cooled.$b$, 'seed 2026-09-29'),
('kitchen', 'Kitchenette', 'public',
 array['kitchen','kitchenette','microwave','fridge','refrigerator','ref','coffee','kettle','electric kettle','utensils','plates','dishes','pagkain','kusina'],
 $b$The kitchenette has an induction cooker, a microwave, a fridge and an electric kettle, with basic cookware, plates and utensils for simple meals. Complimentary coffee and purified drinking water are set out for your arrival. We only ask that the surfaces are wiped and dishes washed after cooking, so the space is ready the next time you need it.$b$, 'seed 2026-09-29'),
('laundry', 'Washing machine (Panasonic NA-F80A5)', 'public',
 array['laundry','washing machine','washer','wash','labada','laba','detergent','sabon','clothes','spin','dryer','drying rack','sampayan'],
 $b$Detergent is not provided, so you may like to bring your own. Load the clothes, then add powder detergent straight into the tub or liquid detergent into its slot. Close the lid and choose your cycle; the machine runs on its own from there. It is a washer only, and a portable drying rack is provided for drying.$b$, 'seed 2026-09-29'),
('iron-steamer', 'Garment steamer', 'public',
 array['iron','steamer','plantsa','wrinkles','crease','press','garment','wardrobe','hangers'],
 $b$For pressing there is a garment steamer rather than a flat iron, stored in the wardrobe cabinet; the wardrobe also has hangers for unpacking. Fill it, let it heat, and keep it moving over the fabric. It is best unplugged as soon as you are done.$b$, 'seed 2026-09-29'),
('air-purifier', 'Air purifier (Simplus)', 'public',
 array['air purifier','purifier','allergy','allergies','dust','air quality','smell','odor','hangin'],
 $b$A Simplus air purifier works quietly in the corner and keeps the air turning over, which you will notice most if you are prone to allergies. It is set up to run on its own, so there is nothing for you to adjust.$b$, 'seed 2026-09-29'),
('ecoflow', 'EcoFlow RIVER 3 power station', 'public',
 array['ecoflow','power station','power bank','battery','backup power','charge phone','brownout','blackout','outage','generator','walang kuryente','walay kuryente'],
 $b$The EcoFlow RIVER 3 sits near the TV unit for outages and is already set up, so you may plug in whenever you need it. Check the display for charge, hold the main button to power it on, press the AC button for the wall sockets, and plug in. It comfortably runs the router (about 26 hours), phones (around 15 charges), an LED lamp, a thin laptop (about 4.5 hours), a stand fan (about 3 hours) or a small TV. It is not for the aircon, water heater, microwave, kettle or induction cooker; its output is 300 W in total. When power returns, plug it into the wall and it recharges in one to two hours.$b$, 'seed 2026-09-29'),
('ecoflow-staff', 'EcoFlow weekly check (staff)', 'staff',
 array['ecoflow check','ecoflow charge','battery level','top up'],
 $b$Check the EcoFlow weekly and keep it above 50 percent; top it up whenever it reads below 30 percent so it is ready for the next brownout. Below 20 percent it is for phones only; store it charged with the vents clear.$b$, 'seed 2026-09-29'),
('power-outage', 'Power outage', 'public',
 array['brownout','blackout','outage','power cut','no power','no electricity','emergency light','lights out','breaker','main breaker','walang kuryente','walay kuryente','kuryente'],
 $b$The area has occasional scheduled power interruptions, and the unit is prepared for them. Water keeps running, the Wi-Fi router has backup power, and a charged emergency light sits on top of the fridge, where you will see it at once. The EcoFlow RIVER 3 near the TV unit keeps phones, laptops and a fan going. The main breaker is by the door, on your left as you face out from inside. If a brownout runs long or anything feels off, a message to us is all it takes.$b$, 'seed 2026-09-29'),
('smart-lock', 'Smart lock entry', 'guest',
 array['door code','passcode','pin code','keypad','smart lock','unlock','open the door','auto lock','ttlock','pinto','pultahan','susi','yawe'],
 $b$Tap the keypad to wake it, enter your code and press #. The door locks itself when it closes, so pull it firmly shut whenever you leave. Your key card, kept with the remotes inside, also opens the door with a tap on the keypad. Your personal code reaches you at least a day before arrival, once your IDs and the balance are in. Should the keypad not respond, message us here or call {{ONGROUND}} and we will get you in.$b$, 'seed 2026-09-29'),
('smart-lock-prospect', 'Self check-in, for prospects', 'public',
 array['self check-in','self check in','check in process','how to check in','late arrival','arrive late','keyless','contactless','smart lock','door lock'],
 $b$Check-in is self-service by smart lock, so a late arrival is easy. Your personal door code is sent at least a day before arrival, once IDs and the balance are in, and the door locks itself behind you. Check-in opens at 2:00 PM.$b$, 'seed 2026-09-29'),
('smart-lock-staff', 'Smart lock, staff notes', 'staff',
 array['ttlock','lock admin','guest code','generate code','code expired','lock battery'],
 $b$The lock is TTLock; guest codes are issued from the TTLock app by the host once IDs and the balance are in, at least 24 hours before arrival. The code itself is never written into Cassy or the manual.$b$, 'seed 2026-09-29'),
('key-card', 'Key card and remotes', 'guest',
 array['key card','keycard','lanyard','keychain','remotes','lost card','lost key','replacement card'],
 $b$Inside, together with the aircon and TV remotes, you will find the access key card on a keychain with the Cascade Hideaway logo. A tap on the keypad unlocks the door with it. Please keep the card and remotes together during your stay; a lost card carries a PHP 1,000 replacement fee.$b$, 'seed 2026-09-29'),
('gate-pod-lock', 'Gate pod lock', 'guest',
 array['pod lock','gate lock','padlock','extra lock','overnight lock','kandado'],
 $b$A pod lock for the front gate is kept indoors with the key card and remotes. It is optional: fit it on the gate for a second layer overnight if you like, and take it off before you head out.$b$, 'seed 2026-09-29'),
('security-gate', 'Village gate on arrival', 'guest',
 array['security gate','village gate','bria homes gate','subdivision entrance','gate pass','guardhouse'],
 $b$At the Bria Homes entrance, tell the security personnel you are a guest at Cascade Hideaway and give the block and lot from your arrival message; they will let you through. Start your GPS before leaving the airport, since Bria Homes has more than one entrance.$b$, 'seed 2026-09-29'),
('parking', 'Parking and CCTV', 'public',
 array['parking','park','car','vehicle','garage','cctv','camera','security','safe car','paradahan','motor','motorcycle','guard'],
 $b$Parking is free, right in front of the unit or alongside it, inside a gated village with a security team at the entry points; one vehicle per reservation. An outdoor CCTV camera watches the parking area around the clock, and it faces outward only - there is no recording of any kind inside the unit. Neighbours fill the nearer spaces by evening, so if you arrive after 8 PM, a word ahead lets us keep a space for you.$b$, 'seed 2026-09-29'),
('privacy-indoors', 'Privacy inside the unit', 'public',
 array['camera inside','hidden camera','microphone','recording','privacy','spy'],
 $b$The one camera is outside and faces the parking area and the approach. There are no cameras, microphones or recording of any kind inside the unit.$b$, 'seed 2026-09-29'),
('check-in-time', 'Check-in and check-out times', 'public',
 array['check-in time','check in time','checkout time','check-out time','2pm','12 noon','early check-in','late checkout','extend','extension'],
 $b$Check-in is from 2:00 PM and check-out is by 12:00 noon. Early check-in and late check-out can be arranged when the calendar allows; we confirm once your dates are set, and a late check-out may carry an additional charge.$b$, 'seed 2026-09-29'),
('check-out', 'Check-out steps', 'public',
 array['check out','checkout','leaving','departure','before leaving','alis','hawa','biyahe','key on departure'],
 $b$Before you leave by noon: collect the trash into the big trash bin, check the rooms for personal belongings, switch off the lights, aircon and appliances, and leave the key card with the remotes where you found them. Then close the door firmly - the lock engages on its own. Thank you for staying with us.$b$, 'seed 2026-09-29'),
('trash', 'Trash and bins', 'public',
 array['trash','garbage','rubbish','bin','bins','basura','waste','segregation','recycle','full bin'],
 $b$Small bins are inside the unit. The one thing we ask is that the trash is collected into the big trash bin before you leave; on longer stays the mid-stay clean takes care of it as well. For the plumbing, toilet paper and sanitary products go in the bathroom bin rather than the toilet.$b$, 'seed 2026-09-29'),
('plumbing', 'Toilet and plumbing', 'public',
 array['toilet','flush','clog','clogged','plumbing','tissue','toilet paper','sanitary','cr','banyo','kubeta'],
 $b$The plumbing is an eco-friendly system, so toilet paper and sanitary products go in the bin provided beside the toilet, not down the bowl. Should the flush or drain misbehave, a message to us brings help quickly.$b$, 'seed 2026-09-29'),
('quiet-hours', 'Quiet hours and gatherings', 'public',
 array['quiet hours','noise','loud','party','gathering','event','celebration','visitors','neighbors','neighbours','10pm','ingay','saba'],
 $b$Quiet hours run from 10:00 PM to 6:00 AM out of consideration for the neighbours. The unit is a private retreat for registered guests, so gatherings and events are not held here; day visitors are welcome with advance notice.$b$, 'seed 2026-09-29'),
('smoking', 'Smoking', 'public',
 array['smoke','smoking','cigarette','vape','vaping','porch','sigarilyo','yosi'],
 $b$Smokers are welcome on the porch. Inside we ask you to refrain, so the linens and the air stay fresh for everyone who follows.$b$, 'seed 2026-09-29'),
('shoes', 'Footwear and slippers', 'public',
 array['shoes','slippers','footwear','shoe rack','tsinelas','sapatos'],
 $b$Footwear comes off at the entrance to keep the floors clean; a shoe rack with complimentary slippers is right by the door.$b$, 'seed 2026-09-29'),
('energy', 'Lights and appliances when out', 'public',
 array['switch off','lights','save energy','electricity','leave the aircon','aircon on when out'],
 $b$When you head out, switching off the lights, aircon and appliances keeps the unit efficient. The aircon cools the room again within minutes when you return.$b$, 'seed 2026-09-29'),
('mid-stay-clean', 'Mid-stay cleaning', 'public',
 array['cleaning','housekeeping','fresh towels','change sheets','linens','restock','mid-stay','mid stay','linis'],
 $b$Stays of 5 nights or more include a complimentary mid-stay refresh: beds and bath refreshed, supplies restocked. Tell us a time that suits you and we will arrange it around your day. Fresh towels or supplies between refreshes are a message away.$b$, 'seed 2026-09-29'),
('bedding', 'Beds and the pull-out', 'public',
 array['bed','beds','queen','pull-out','pullout','underbed','extra bed','mattress','third guest','kama','higaan'],
 $b$The queen bed is dressed in hotel-grade linens, and a single pull-out bed stores neatly beneath it for a third guest, made up with the same linens. It slides straight out from under the queen when needed.$b$, 'seed 2026-09-29'),
('workspace', 'Workspace', 'public',
 array['workspace','desk','work','table','laptop','office','chair','wfh'],
 $b$A dedicated workspace with comfortable seating and a clear surface is set up for work or planning your days, with the fibre Wi-Fi beside it.$b$, 'seed 2026-09-29'),
('emergency', 'Emergency numbers', 'public',
 array['emergency','911','police','fire','ambulance','hospital','doctor','medical','sick','injured','accident','hotline','tulong','tabang'],
 $b$For any life-threatening emergency, dial 911 first, then let us know. Police hotline 0998-598-7207; Bureau of Fire Protection 160. The nearest 24-hour emergency room is St. Elizabeth Hospital on the National Highway at Santiago Boulevard, (083) 552-3162, patient care mobile +63 962 316 0213 or 0214. The main breaker is by the door, on your left as you face out from inside, and an emergency light sits on top of the fridge. We are reachable day and night, and {{ONGROUND}} can come to the unit if you need someone there.$b$, 'seed 2026-09-29'),
('earthquake', 'Earthquake and natural events', 'public',
 array['earthquake','lindol','linog','tremor','shaking','tsunami','typhoon','bagyo','flood','baha','aftershock','evacuate'],
 $b$During shaking: drop, cover under a sturdy table, and hold on; stay clear of windows and tall furniture, and if you are in bed, stay there with a pillow over your head. Afterwards, put shoes on before walking in case of glass, and expect aftershocks. If it feels unsafe, step outside calmly with your phone, the key card and an ID, and gather in the open away from walls and power lines; near the shoreline after strong or long shaking, move inland or uphill without waiting for a siren. If you can do it safely, switch off the main breaker (by the door, on your left as you face out from inside), use your phone light rather than candles, and message us straight away - we will guide you step by step.$b$, 'seed 2026-09-29'),
('flooding', 'Heavy rain and the road in', 'public',
 array['rain','flood','flooding','baha','road','access road','storm','bagyo'],
 $b$On heavy-rain days the road into Bria Homes can flood on and off. If you are arriving in a downpour, a message lets us tell you how the road looks and suggest a timing.$b$, 'seed 2026-09-29'),
('address-staff', 'Property address (staff)', 'staff',
 array['address','block','lot','blk','full address','location','exact address'],
 $b$Block 47 Lot 39, Bria Homes, Conel Road, Barangay San Isidro, General Santos City 9500. The block and lot are given to guests by the host after confirmation, never by the Messenger concierge.$b$, 'seed 2026-09-29'),
('ac-water-failure-staff', 'Aircon or water failure (staff)', 'staff',
 array['aircon broken','no water','water failure','aircon not cooling','technician','tech','sira','guba'],
 $b$First establish whether it is the unit or an area outage. Within fifteen minutes, message the guest with an apology, the technician's ETA and the stopgap provided (a fan or bottled water). Dispatch the technician; if it is not resolved in three to four hours, offer relocation help or a partial refund for the night and tell Lloyd.$b$, 'seed 2026-09-29'),
('turnover-sop-staff', 'Turnover sequence (staff)', 'staff',
 array['turnover','cleaning checklist','sop','phases','strip linens','staging','honey','cleaning app'],
 $b$Phase 1, entry and reset: open the windows, photograph any damage before cleaning, strip and bag all linens. Phase 2, deep clean: bathroom first (let the cleaner sit five minutes), then kitchenette (dishes, degrease the cooker, sanitise sink and counters, wipe inside the microwave and the fridge handles), then dust top to bottom and sanitise remotes, switches and handles. Phase 3, staging: hotel-style bed, aircon to 28 C, heater off, key card with the remotes, and submit the report in the Cleaning Checklist app.$b$, 'seed 2026-09-29'),
('supplier-contacts-staff', 'Supplier and service contacts (staff)', 'staff',
 array['supplier','plumber','electrician','aircon cleaning','technician contact','isp','laundry service','pest control'],
 $b$Not yet recorded. Lloyd or Marifel can teach them in the Finance chat: "cassy teach: <supplier, number, what they do>".$b$, 'seed 2026-09-29')
on conflict (topic) do update set
  title = excluded.title, body = excluded.body, keywords = excluded.keywords, tier = excluded.tier,
  is_active = true, updated_by = excluded.updated_by, updated_at = now();

commit;
